### ISSUE TITLE
Does this license have a license?

### ISSUE THREAD

**Issue by timmc** [berneout/big-time-public-license#12]
For example, if someone wanted to make different inclusions or exclusions in the noncommercial language or the permitted licensors, could they do so?

(I'm guessing that publishing a different version under a different name would be fine in practice, but there's no statement of that.)

**Comment by kemitchell** [comment]
Sure. Do what you like with the text, but please rename and otherwise make clear that your "fork" is not the Big Time License.

If you think your edits might be appropriate changes to a future version of Big Time, feel free to send PRs!

**Comment by timmc** [comment]
I'm asking out of curiosity, and a bit of confusion. Many software licenses I see have a tiny bit about the copyright of the license, so I was surprised not to see it here. Is this the informal "lawyers tend not to treat small chunks of contracts and licenses as falling under copyright" thing? :-)
