### ISSUE TITLE
Sample commercial license

### ISSUE THREAD

**Issue by pointlessone** [berneout/big-time-public-license#14]
It appears to me that this license is not too useful on its own. Without the commercial license this is not too different from a whole lot of permissive licenses out there in practice.

I understand that putting together a comprehensive commercial license is a lot of work but maybe you cold do a simple sample one or point to already available ones that could be used (either as is or as a template).

**Comment by kemitchell** [comment]
There are many form license agreements online. I have published at least a couple, and plan to publish more.
