### ISSUE TITLE
Is the Warranty Waiver insufficient?

### ISSUE THREAD

**Issue by namandixit** [berneout/big-time-public-license#15]
On the recent Hacker News [thread](https://news.ycombinator.com/item?id=29924637) about this license, there was [a comment](https://news.ycombinator.com/item?id=29930162) made regarding the warranty waiver clause:

> The general consensus is that AS IS isn't enough to protect you against implied warranties, because - despite the language of the UCC - some courts are freaking idiots.
> 
> https://casetext.com/case/gaylord-v-lawler-mobile-homes-inc
> 
> Why did you choose not to disclaim the big four implied warranties that nearly all open source licenses disclaim?
> 
> Even BSD (the worst drafted license ever) explicitly disclaims two of the four (MIT and some forms of ISC get all three that realistically would apply to non-tangible property, and Apache 2.0 disclaims all four just to be safe). So it's a bit of a head-scratcher why you'd draft a license that incurs that legal risk. 

I am not knowledgable enough to tell if the concern expressed here is valid or not; but I wanted to bring it to your attention, and ask your opinion on the accuracy of this, as well as whether the clause is liable to be problematic.

-------------------

For reference, appended are the warranty waiving clauses from the referenced licenses:

**MIT License**

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Apache License 2.0**

> 7. Disclaimer of Warranty. Unless required by applicable law or agreed to in writing, Licensor provides the Work (and each Contributor provides its Contributions) on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing the Work and assume any risks associated with Your exercise of permissions under this License.
> 
> 8. Limitation of Liability. In no event and under no legal theory, whether in tort (including negligence), contract, or otherwise, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall any Contributor be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this License or out of the use or inability to use the Work (including but not limited to damages for loss of goodwill, work stoppage, computer failure or malfunction, or any and all other commercial damages or losses), even if such Contributor has been advised of the possibility of such damages.
> 
> 9. Accepting Warranty or Additional Liability. While redistributing the Work or Derivative Works thereof, You may choose to offer, and charge a fee for, acceptance of support, warranty, indemnity, or other liability obligations and/or rights consistent with this License. However, in accepting such obligations, You may act only on Your own behalf and on Your sole responsibility, not on behalf of any other Contributor, and only if You agree to indemnify, defend, and hold each Contributor harmless for any liability incurred by, or claims asserted against, such Contributor by reason of your accepting any such warranty or additional liability.

**Comment by kemitchell** [comment]
Thanks for letting me know. I've responded on HN.

**Comment by namandixit** [comment]
Thanks, closing the issue.
